#!/usr/bin/env bash

## Author  : Aditya Shakya
## Twitter : @adi1090x
## Github  : @adi1090x
## Reddit  : @adi1090x

## Termite style uninstall script

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"

## Banner
banner () {
    clear
    echo "
    ${RED}┌──────────────────────────────────────────────────────┐
    │░░░▀█▀░█▀▀░█▀▄░█▄█░▀█▀░▀█▀░█▀▀░░░█▀▀░▀█▀░█░█░█░░░█▀▀░░│
    │░░░░█░░█▀▀░█▀▄░█░█░░█░░░█░░█▀▀░░░▀▀█░░█░░░█░░█░░░█▀▀░░│
    │░░░░▀░░▀▀▀░▀░▀░▀░▀░▀▀▀░░▀░░▀▀▀░░░▀▀▀░░▀░░░▀░░▀▀▀░▀▀▀░░│
    └──────────────────────────────────────────────────────┘
    ${ORANGE}[*] ${CYAN}By- Aditya Shakya // adi1090x"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "${RED}\n\n%s\n" "    [*] Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "${RED}\n\n%s\n" "    [*] Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Check for previous installation
uninstall_tstyle () {
	banner
	if [[ (-L /usr/bin/termite-style) && (-d /usr/share/termite-style) ]]; then
		{ echo; echo ${ORANGE}"    [*] Uninstalling termite-style..."; echo; }
		{ echo ${ORANGE}"    [*] Removing files from '/usr/share' dir."${BLUE}; }
		{ printf "    "; sudo rm -r /usr/share/termite-style /usr/share/fonts/termite-style /usr/bin/termite-style; sudo fc-cache; }
		# Verify files
		if [[ (! -L /usr/bin/termite-style) && (! -d /usr/share/termite-style) ]]; then
			{ echo; echo ${GREEN}"    [*] Uninstalled Successfully."; echo; }
			{ reset_color; exit 0; }
		else
			{ echo ${RED}"    [!] Error Occured."; echo; reset_color; exit 1; }
		fi
	else
		{ echo; echo ${RED}"    [!] ${MAGENTA}termite-style ${GREEN}is not installed."; echo; }
		{ reset_color; exit 0; }
	fi
}

uninstall_tstyle